### ISSUE TITLE
preprocess_sent_label.py此文件运行错误

### ISSUE THREAD

**Issue by LGDEMO** [TysonYu/Laysumm#1]
你好，很高兴你能开源你的代码，我对你今年发表的《Dimsum @LaySumm 20: BART-based Approach for Scientific Document  Summarization》这篇论文很感兴趣，我现在也要生成label标签，但是运行报错，所以请教一下你，希望你得到你的帮助，谢谢！！！！

Traceback (most recent call last):
  File "D:/Python_WorkSpace/Laysumm/BART/preprocess_sent_label.py", line 258, in <module>
    rouge = nlp.load_metric('rouge') 
  File "D:\Anaconda3\envs\myenv\lib\site-packages\nlp\load.py", line 442, in load_metric
    module_path, hash = prepare_module(path, download_config=download_config, dataset=False)
  File "D:\Anaconda3\envs\myenv\lib\site-packages\nlp\load.py", line 303, in prepare_module
    f"To be able to use this {module_type}, you need to install the following dependencies"
ImportError: To be able to use this metric, you need to install the following dependencies['absl', 'rouge_score', 'rouge_score'] using 'pip install # Here to have a nice missing dependency error message early on rouge_score rouge_score' for instance'

**Comment by TysonYu** [comment]
Hi, 
Thank you for your interest in our paper.
From the error message. It seems you didn't install the rouge metric correctly. The rouge we use here is based on this tool: [huggingface nlp](https://github.com/huggingface/datasets/blob/master/metrics/rouge/rouge.py). You can check this issue [How to get ROUGE-2 with the ROUGE metric ?](https://github.com/huggingface/datasets/issues/216#issuecomment-635959530) to learn how to use the metric.
